export const SELECT_UNIT = "SELECT_UNIT",
  SELECT_GENDER = "SELECT_GENDER",
  SET_HEIGHT = "SET_HEIGHT",
  SET_WEIGHT = "SET_WEIGHT",
  SELECT_TRAINING = "SELECT_TRAINING",
  CALCULATE_GOAL = "CALCULATE_GOAL",
  SET_GOAL = "SET_GOAL",
  REGISTER = "REGISTER";
