export const GET_USER_SETTING = "GET_USER_SETTING",
  SAVE_GOAL = "SAVE_GOAL",
  SET_NOTI_ALLOWANCE = "SET_NOTI_ALLOWANCE",
  SET_NOTI_START_TIME = "SET_NOTI_START_TIME",
  SET_NOTI_END_TIME = "SET_NOTI_END_TIME",
  SET_NOTI_PERIOD = "SET_NOTI_PERIOD";
